//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigTravel_Company.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Payment = new HashSet<Payment>();
            this.reis = new HashSet<reis>();
        }
    
        public int id_orders { get; set; }
        public int id_customer { get; set; }
        public int id_employes { get; set; }
        public int id_vouchers { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]

        public System.DateTime Date_registration { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> idOrder_status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employes Employes { get; set; }
        public virtual Order_status Order_status { get; set; }
        public virtual Vouchers Vouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reis> reis { get; set; }
    }
}
