//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigTravel_Company.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        public int idPayment { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> id_orders { get; set; }
        public string bank_card_num { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]

        public Nullable<System.DateTime> date_payment { get; set; }
        public Nullable<int> Id_PayType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
