//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigTravel_Company.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reis
    {
        public int id_reis { get; set; }
        public Nullable<int> id_order { get; set; }
        public string Point_departure { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> Departure_date { get; set; }
        public Nullable<System.DateTime> Date_arrival { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
